<?php
declare(strict_types=1);
function requestedRoles(): array { return ['fleet_manager'=>'Fleet Manager','dispatcher'=>'Dispatcher','safety_officer'=>'Safety Officer','financial_analyst'=>'Financial Analyst','driver'=>'Driver']; }
function registerPendingUser(array $data): void {
    $email=trim((string)($data['email']??'')); $first=trim((string)($data['first_name']??'')); $last=trim((string)($data['last_name']??'')); $role=(string)($data['role']??''); $password=(string)($data['password']??'');
    if(!$first||!$last||!filter_var($email,FILTER_VALIDATE_EMAIL)||!isset(requestedRoles()[$role])||passwordPolicyError($password)!==null||!hash_equals($password,(string)($data['password_confirmation']??''))) throw new InvalidArgumentException('Please complete all required fields with a valid password and requested role.');
    $check=getDb()->prepare('SELECT 1 FROM users WHERE email=?');$check->execute([$email]);if($check->fetch())throw new InvalidArgumentException('An account already uses this email address.');
    $stmt=getDb()->prepare('INSERT INTO users (uuid,first_name,last_name,full_name,email,phone,password_hash,role,status,employee_id,department,address,city,state,country,approval_status,is_active) VALUES (UUID(),?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'Pending\',0)');
    $stmt->execute([$first,$last,$first.' '.$last,$email,trim((string)($data['phone']??'')),password_hash($password,PASSWORD_DEFAULT),$role,'Inactive',trim((string)($data['employee_id']??'')),trim((string)($data['department']??'')),trim((string)($data['address']??'')),trim((string)($data['city']??'')),trim((string)($data['state']??'')),trim((string)($data['country']??''))]);
    logActivity('User registered','Pending approval: '.$email.' from '.clientIp());
}
function approvalAccess(array $target): bool { $role=currentUser()['role']??''; return $role==='admin'||($role==='fleet_manager' && in_array($target['role'],['dispatcher','safety_officer','financial_analyst','driver'],true)); }
function decideUserApproval(int $id,string $decision,string $reason=''): void { $target=getDb()->prepare('SELECT id,email,full_name,role FROM users WHERE id=? AND approval_status="Pending"');$target->execute([$id]);$user=$target->fetch();if(!$user||!approvalAccess($user))throw new RuntimeException('This request cannot be approved by your account.');if($decision==='Approved'){getDb()->prepare('UPDATE users SET approval_status="Approved",approved_by=?,approved_at=NOW(),is_active=1,status="Active" WHERE id=?')->execute([currentUser()['id'],$id]);$message='Your account has been approved. You can now login.';$subject='Account Approved';}else{if(trim($reason)==='')throw new InvalidArgumentException('A rejection reason is required.');getDb()->prepare('UPDATE users SET approval_status="Rejected",rejected_by=?,rejected_at=NOW(),rejection_reason=?,is_active=0,status="Inactive" WHERE id=?')->execute([currentUser()['id'],$reason,$id]);$message='Your account registration has been rejected. Reason: '.$reason;$subject='Account Rejected';}getDb()->prepare('INSERT INTO notifications (user_id,title,message) VALUES (?,?,?)')->execute([$id,$subject,$message]);sendMail($user['email'],$subject,'<p>'.e($message).'</p>');logActivity('User '.$decision,strtolower($decision).' '.$user['email'].' from '.clientIp());}
