<?php
/** Maintenance planning, execution and cost-reporting service. */
declare(strict_types=1);require_once __DIR__.'/maintenance_validation.php';
function getMaintenanceById(int $id): ?array {$s=getDb()->prepare('SELECT m.*,v.registration_number,v.make,v.model FROM maintenance_logs m JOIN vehicles v ON v.id=m.vehicle_id WHERE m.id=? AND m.deleted_at IS NULL');$s->execute([$id]);return $s->fetch()?:null;}
function saveMaintenance(array $input, ?int $id = null): array
{
    $errors = validateMaintenanceInput($input); if ($errors) return [false, $errors];
    $optional = static fn (string $key): ?string => (($value = trim((string)($input[$key] ?? ''))) === '') ? null : $value;
    $data = ['vehicle_id'=>(int)$input['vehicle_id'], 'maintenance_type'=>$input['maintenance_type'], 'priority'=>$input['priority'] ?? 'Medium', 'vendor_name'=>$optional('vendor_name'), 'mechanic_name'=>$optional('mechanic_name'), 'description'=>trim((string)$input['description'],), 'estimated_cost'=>(float)($input['estimated_cost'] ?? 0), 'cost'=>(float)($input['cost'] ?? $input['estimated_cost'] ?? 0), 'scheduled_date'=>$input['scheduled_date'], 'expected_completion_date'=>$optional('expected_completion_date'), 'remarks'=>$optional('remarks')];
    if ($id) { $set=[]; foreach($data as $key=>$value) $set[]="$key=?"; getDb()->prepare('UPDATE maintenance_logs SET '.implode(',',$set).' WHERE id=?')->execute([...array_values($data),$id]); logActivity('Maintenance updated','Maintenance #'.$id); return [true,$id]; }
    $data['uuid']=bin2hex(random_bytes(16)); $data['maintenance_code']='MNT-'.date('Y').'-'.strtoupper(bin2hex(random_bytes(3))); $data['status']='Scheduled'; $cols=array_keys($data); getDb()->prepare('INSERT INTO maintenance_logs ('.implode(',',$cols).') VALUES ('.implode(',',array_fill(0,count($cols),'?')).')')->execute(array_values($data)); $new=(int)getDb()->lastInsertId(); logActivity('Maintenance scheduled','Maintenance #'.$new); return [true,$new];
}
function changeMaintenanceStatus(int $id,string $status): array {$record=getMaintenanceById($id);if(!$record)return [false,'Maintenance record not found.'];if(!in_array($status,['Scheduled','In Progress','Completed','Cancelled'],true))return [false,'Invalid maintenance status.'];if($record['status']==='Completed')return [false,'Completed maintenance cannot be changed.'];getDb()->prepare('UPDATE maintenance_logs SET status=?,start_date=CASE WHEN ?="In Progress" AND start_date IS NULL THEN CURDATE() ELSE start_date END,completed_date=CASE WHEN ?="Completed" THEN CURDATE() ELSE completed_date END WHERE id=?')->execute([$status,$status,$status,$id]);if($status==='In Progress')getDb()->prepare('UPDATE vehicles SET status="In Shop" WHERE id=? AND status<>"Retired"')->execute([$record['vehicle_id']]);if($status==='Completed')getDb()->prepare('UPDATE vehicles SET status="Available" WHERE id=? AND status="In Shop"')->execute([$record['vehicle_id']]);if($status==='Cancelled'&&$record['status']==='In Progress')getDb()->prepare('UPDATE vehicles SET status="Available" WHERE id=? AND status="In Shop"')->execute([$record['vehicle_id']]);logActivity('Maintenance status changed',"Maintenance #$id set to $status");return [true,'Maintenance status updated.'];}
function maintenanceSummary(): array {return getDb()->query('SELECT COUNT(*) total,SUM(status="Scheduled") scheduled,SUM(status="In Progress") active,SUM(status="Completed") completed,COALESCE(SUM(cost),0) total_cost FROM maintenance_logs WHERE deleted_at IS NULL')->fetch()?:[];}
