<?php
/** Card shell. Set $cardTitle and $cardContent (safe markup generated by application code). */
declare(strict_types=1);
?>
<section class="card"><?php if (!empty($cardTitle)): ?><h2><?= e((string)$cardTitle) ?></h2><?php endif; ?><?= (string)($cardContent ?? '') ?></section>
